# Generated by Django 4.2.6 on 2024-03-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_management', '0002_alter_ticket_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'Requested'), (1, 'Approved'), (2, 'Consumed'), (5, 'Rejected')], default=0),
        ),
    ]
