# Generated by Django 4.2.7 on 2024-04-04 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_management', '0004_deviceregistration_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceregistration',
            old_name='token',
            new_name='device_token',
        ),
    ]
