# Generated by Django 4.2.7 on 2024-04-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_management', '0007_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
