# Generated by Django 4.2.7 on 2024-04-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_management', '0008_notification_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deviceregistration',
            table='device_registrations',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='tickets',
        ),
    ]
