# Generated by Django 4.2.6 on 2024-05-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_management', '0009_alter_deviceregistration_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceregistration',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Organisation')], default=1),
        ),
    ]
