# Generated by Django 4.2.7 on 2024-05-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payments',
            table='payments',
        ),
    ]
