# Generated by Django 4.2.6 on 2024-03-05 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_management', '0001_initial'),
        ('exam_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_management.questions'),
        ),
    ]
