# Generated by Django 4.2.6 on 2024-03-15 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject_management', '0001_initial'),
        ('exam_management', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'drafted'), (1, 'confirmed'), (2, 'completed'), (3, 'evaluated'), (4, 'result_published')], default=0),
        ),
        migrations.AlterField(
            model_name='examsubjects',
            name='difficulty_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'easy'), (2, 'medium'), (3, 'difficult')], null=True),
        ),
        migrations.AlterField(
            model_name='examsubjects',
            name='pass_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='examsubjects',
            name='question_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='examsubjects',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='subject_management.subject'),
        ),
        migrations.AlterField(
            model_name='examsubjects',
            name='time_duration',
            field=models.IntegerField(blank=True),
        ),
    ]
