# Generated by Django 4.2.7 on 2024-04-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0004_alter_exam_scheduled_time_alter_exam_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'drafted'), (1, 'confirmed'), (2, 'completed'), (3, 'evaluated'), (4, 'result_published'), (5, 'cancelled')], default=0),
        ),
    ]
