# Generated by Django 4.2.7 on 2024-04-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0005_alter_exam_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exam',
            table='exams',
        ),
        migrations.AlterModelTable(
            name='examquestions',
            table='exam_questions',
        ),
        migrations.AlterModelTable(
            name='examsubjects',
            table='exam_subjects',
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='feedbacks',
        ),
    ]
