# Generated by Django 4.2.6 on 2024-03-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_answer', models.CharField(blank=True, max_length=1025, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks_scored', models.IntegerField(default=0)),
            ],
        ),
    ]
