# Generated by Django 4.2.6 on 2024-03-05 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatemanagement', '0002_initial'),
        ('question_management', '0001_initial'),
        ('examanswers_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateanswers',
            name='Selective_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question_management.questionoptions'),
        ),
        migrations.AddField(
            model_name='candidateanswers',
            name='exam_candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatemanagement.examcandidate'),
        ),
        migrations.AddField(
            model_name='candidateanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_management.questions'),
        ),
    ]
