# Generated by Django 4.2.7 on 2024-03-14 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_management', '0002_alter_freeanswers_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_description',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
