# Generated by Django 4.2.7 on 2024-04-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_management', '0004_alter_questions_marks'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questions',
            table='Questions',
        ),
    ]
