# Generated by Django 4.2.7 on 2024-04-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_management', '0005_alter_questions_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='freeanswers',
            table='free_answers',
        ),
        migrations.AlterModelTable(
            name='questionoptions',
            table='question_options',
        ),
        migrations.AlterModelTable(
            name='questions',
            table='questions',
        ),
    ]
