# Generated by Django 4.2.6 on 2024-04-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_login_provider',
            field=models.BooleanField(default=False),
        ),
    ]
