# Generated by Django 4.2.7 on 2024-04-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_user_external_login_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='otp',
            table='otp',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
